config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {
    sessions:             'users/sessions',
    passwords:            'users/passwords',
    registrations:        'users/registrations',
    confirmations:        'users/confirmations',
    ominiauth_callbacks:  'users/ominiauth_callbacks',
    unlocks:              'users/unlocks'
  }
  root 'home#index'

  resources :articles do 
    resources :comments
  end
  resources :users do 
    member do 
      get   :change_role
      patch :update_role
      get   :change_status
      patch :update_status
    end
    collection do 
      post  :create_user
      patch :update_user
    end
  end

  resources :comment_feedbacks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article, optional: true
  belongs_to :user, optional: true
  has_many :comment_feedbacks
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article), flash: { success: "Comment has been posted successfully" }
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), flash: { success: "Comment has been posted successfully" }
  end
 
  private
    def comment_params
      params.require(:comment).permit(:user_id, :comment_text)
    end
end

app/views/comments/_comment.html.erb
<div class="row mt-3 mb-3">
  <div class="col-12">
    <div class="media">
      <%= image_tag "user.png", class: "mr-3", style: "width:50px;" %>
      <div class="media-body">
        <h5 class="mt-0"><%= comment.user.name %></h5>
        <%= comment.comment_text %>
        <div class="row">
          <div class="col-md-6">
            <%= comment.created_at.strftime("%b, %d, %Y")%>
          </div>
          <div class="col-md-6">
            <% if can? :manage, comment.article %>
              <%= link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
              <%= link_to 'Reply', new_comment_feedback_path(comment_id: comment.id, user_id: @article.user.id), class: "btn btn-sm btn-success", remote: true %>
            <% end %>
          </div>
        </div>
        <% if comment.comment_feedbacks.present? %>
          <% comment.comment_feedbacks.each do |feedback| %>
            <p><%= feedback.title %> <%= image_tag "user.png", class: "mr-3", style: "width:30px;" %></p>
          <% end %>
        <% end %>
        <div id="feedBackForm_<%= comment.id %>"></div>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id if user_signed_in? %>  
  <div class="form-group">
    <%= form.label 'Write a Comment' %>
    <%= form.text_area :comment_text, class: "form-control", rows: "5" %>
  </div>
  <div class="form-group">
    <%= form.submit "Sumbit", class: "btn btn-primary" %>
  </div>
<% end %>