config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {
    sessions:             'users/sessions',
    passwords:            'users/passwords',
    registrations:        'users/registrations',
    confirmations:        'users/confirmations',
    ominiauth_callbacks:  'users/ominiauth_callbacks',
    unlocks:              'users/unlocks'
  }
  root 'home#index'

  resources :articles do 
    resources :comments
  end
  resources :users do 
    member do 
      get   :change_role
      patch :update_role
      get   :change_status
      patch :update_status
    end
    collection do 
      post  :create_user
      patch :update_user
    end
  end

  resources :comment_feedbacks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_flash.html.erb
<div id="flash" class='text-center'>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %>">
      <% unless value == true  %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= value %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Bloggers</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <% if can? :manage, User %>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.name, "", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>