config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {
    sessions:             'users/sessions',
    passwords:            'users/passwords',
    registrations:        'users/registrations',
    confirmations:        'users/confirmations',
    ominiauth_callbacks:  'users/ominiauth_callbacks',
    unlocks:              'users/unlocks'
  }
  root 'home#index'

  resources :articles do 
    resources :comments
  end
  resources :users do 
    member do 
      get   :change_role
      patch :update_role
      get   :change_status
      patch :update_status
    end
    collection do 
      post  :create_user
      patch :update_user
    end
  end

  resources :comment_feedbacks

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles, dependent: :destroy       
  has_many :comments, dependent: :destroy
  has_many :comment_feedbacks       


  ROLES = %i[admin author default]
  STATUS = %i[active inactive blocked]

  after_create :set_default_role

  def set_default_role
    self.update(role: 'default')
  end

  def admin?
    self.role == 'admin'
  end

  def author?
    self.role == 'author'
  end

  def default?
    self.role == 'default'
  end
         
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_cofirmation, :role])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_cofirmation, :role])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource

  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :set_user, only: [:destroy, :change_role, :update_role, :change_status, :update_status]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create_user
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, flash: { success: "User has been created successfully" }
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, flash: { success: "User has been destroyed successfully" }
  end

  def change_role
  end

  def update_role
    @user.update(user_role_param)
    redirect_to users_path, flash: { success: "Role for #{@user.name} has been changed successfully" }
  end

  def change_status
  end

  def update_status
    @user.update(user_status_param)
    redirect_to users_path, flash: { success: "Status for #{@user.name} has been changed successfully" }
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit!
    end

    def user_role_param
      params.require(:user).permit(:role)
    end

    def user_status_param
      params.require(:user).permit(:status)
    end

end

app/views/users/_change_role.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_for @user, url: :update_role_user, method: :patch do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :role %>
          <%= f.collection_select(:role, User::ROLES, :to_s, lambda{|i| i.to_s.humanize}, {prompt: "Select role"}, {class: "form-control"}) %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Change Role</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_change_status.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Update Status</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_for @user, url: :update_status_user, method: :patch do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :status %>
          <%= f.collection_select(:status, User::STATUS, :to_s, lambda{|i| i.to_s.humanize}, {prompt: "Select status"}, {class: "form-control"}) %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Change Status</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, url: :create_user_users, method: :post do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %>
    <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :role %>
    <%= f.collection_select(:role, User::ROLES, :to_s, lambda{|i| i.to_s.humanize}, {prompt: "Select role"}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>

<% end %>

app/views/users/change_role.js.erb
$("#changeRole").html("<%= escape_javascript render(partial: 'users/change_role') %>");
$("#changeRole").modal('show');

app/views/users/change_status.js.erb
$("#changeStatus").html("<%= escape_javascript render(partial: 'users/change_status') %>");
$("#changeStatus").modal('show');

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 mx-md-auto">
      <%= link_to "Create User", new_user_path, class: "btn btn-primary float-right mb-4" %>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.role.capitalize %></td>
              <td>
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Action
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' },class: "dropdown-item"  %>
                    <%= link_to 'Change Role', change_role_user_path(user),class: "dropdown-item", data: { toggle: "modal", target: "#changeRole", remote: true }  %>
                    <%= link_to 'Change Status', change_status_user_path(user),class: "dropdown-item", data: { toggle: "modal", target: "#changeStatus", remote: true }  %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="modal fade" id="changeRole" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>

<div class="modal fade" id="changeStatus" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
</div>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-9 mx-md-auto">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">New User</h5>
        </div>
        <div class="card-body">
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>